### ISSUE TITLE
"Pip subprocess error " in Step 7 during Installation 

### ISSUE THREAD

**Issue by wangrong007** [xtorker/PCCArena#3]
Platform: Ubuntu 20.04
I followed the steps until I was stuck in step 7. The attachment is the stdout and stderr dumped during the installation.

[stdout.txt](https://github.com/xtorker/PCCArena/files/8798345/stdout.txt)

[stderror.txt](https://github.com/xtorker/PCCArena/files/8798349/stderror.txt)

**Comment by xtorker** [comment]
duplicated
