### ISSUE TITLE
"Pip subprocess error " in Step 7 during Installation 

### ISSUE THREAD

**Issue by wangrong007** [xtorker/PCCArena#4]
Platform: Ubuntu 20.04
I followed the steps until I was stuck in step 7. 
When I comment out tensorflow-gpu ==1.15.0 for GeoCNNv2. yml
The attachment is the stdout and stderr dumped during the installation.

[stdout.txt](https://github.com/xtorker/PCCArena/files/8798401/stdout.txt)

[stderror.txt](https://github.com/xtorker/PCCArena/files/8798402/stderror.txt)

**Comment by xtorker** [comment]
nbformat 5.1.2 is yanked, updated with 5.1.3.
fd45acb fixed.

**Comment by wangrong007** [comment]
Thanks. I'll give it a try.
